services:
  # 后端服务
  backend:
    image: youtubeplanner-backend:latest
    container_name: youtubeplanner-backend-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION=3600
      - JWT_REFRESH_TOKEN_EXPIRATION=604800
      - CORS_ALLOWED_ORIGINS=http://${EC2_PUBLIC_IP}:3000,http://${EC2_PUBLIC_IP}
    volumes:
      - backend_logs:/app/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - youtubeplanner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端服务
  frontend:
    image: youtubeplanner-frontend:latest
    container_name: youtubeplanner-frontend-prod
    ports:
      - "80:80"
      - "3000:80"
    environment:
      - REACT_APP_API_BASE_URL=http://${EC2_PUBLIC_IP}:8080/api/v1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - youtubeplanner-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nginx反向代理 (可选)
  nginx:
    image: nginx:alpine
    container_name: youtubeplanner-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - youtubeplanner-network
    restart: unless-stopped
    profiles:
      - ssl

networks:
  youtubeplanner-network:
    driver: bridge

volumes:
  backend_logs:
    driver: local 