mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.youtubeplanner.backend.script.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token:
    expiration: 3600  # 1小时
  refresh-token:
    expiration: 604800  # 7天

logging:
  level:
    root: INFO
    com.youtubeplanner.backend: DEBUG
    com.youtubeplanner.backend.script: DEBUG
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log 