services:
  - type: web
    name: youtubeplanner-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -l 3000 -c serve.json
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://youtubeplanner-backend.onrender.com/api/v1
    healthCheckPath: /
    plan: free 